name: meshcnn
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - cython
  - pytorch=1.3.1
  - numpy=1.17.0
  - matplotlib=3.1.3
  - torchvision=0.4.2
  - pip 
  - pip:
    # - git+https://github.com/lanpa/tensorboardX.git
    - pytest==5.1.1
